# Generated by Django 5.1.1 on 2024-10-07 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0012_module_quizzes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="modules",
            field=models.ManyToManyField(blank=True, to="courses.module"),
        ),
        migrations.AlterField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="courses.quiz",
            ),
        ),
    ]
